# Define the train parameters to be passed in TorchTrainer.
train_loop_config:
  input_size: 224
  lr: 0.001
  momentum: 0.9
  batch_size: 32
  num_epochs: 10

# Define the Scaling config parameters.
scaling_config:
  num_workers: 2
  use_gpu: True
  resources_per_worker:
    CPU: 1
    GPU: 1

# Define the other variables based on the local system.
mlflow_config:
    # name of the experiment
    name: "tuning-resnet"
    
    # path to set the mlflow tracking uri
    mlflow_path: "/home/dhaval/Projects/NewRay/results/mlflow_results"
    
    # path to store results from ray session.
    ray_path: "/home/dhaval/Projects/NewRay/results/ray_results"
    
    # path where the local data is stored (if any)
    data_path: "/home/dhaval/Projects/NewRay/data"
    
    # num of tuning trials when running the tune_engine.
    num_runs: 5
   